### ISSUE TITLE
Can't load external on Windows 10 64bit

### ISSUE THREAD

**Issue by alfonso73** [mganss/pdjs#2]
Hi, pd can't create the [js] object on Win10 64bit.
thanks and bests

**Comment by mganss** [comment]
You might need to declare the path to pdjs using `[declare -path pdjs]`.

**Comment by alfonso73** [comment]
I did it but no luck at first. Then i realized that obviously i need to have a .js file in the same place/directory level where i have the patch. BTW the help file for js does nothing and seems a blank patch that can't be maximized, but if i make a new patch with the same js-help.js file and copy at my patch level everything works. So basically what's not working now on Win10 is calling the help for js. I'd add a mechanism in the external that instantiate anyway the [js ] object even if no js file is given as an argument.

**Comment by mganss** [comment]
Does the help file not work even though the `[js]` object has been successfully created?

**Comment by alfonso73** [comment]
It only works if I save a patch and in the same directory where the patch is I put the js-help.js. So it seems that js-help.js can't be find by PD even if it is in its path. Probably this is the cause of the js-help.pd patch being open minimized and blank.

**Comment by mganss** [comment]
Strange, I can't repro. How did you declare the path to pdjs?
My steps to repro:
1. Create new patch
2. Save
3. Create empty test.js file in same folder as patch
4. Add `[declare -path pdjs]`
5. Add `[js test.js]` (object successfully created)
6. Right-click `js` object and select help

**Comment by alfonso73** [comment]
Steps from 1 to 5 are ok.
But 6 open a blank minimized patch...watch the video here that shows what's going on
https://youtu.be/OK_ENszZNUU

**Comment by mganss** [comment]
I think I know what might be going on: The help patch window is offscreen. PD saves the window position in the patch file and I probably saved it last with an X offset that is offscreen on a single monitor. You can either Shift+right-click on the icon in the task bar, select Move from the context menu and move the window to the left using the left arrow key or open js-help.pd in a text editor and set the X coordinate to a low value.

**Comment by alfonso73** [comment]
right! fixed! And as a final comment i'd say
1. let [js] instantiate even if no argument is given or if the js file does not exist.
2. a way to open the .js file with an [ open (  message would be great

thanks!

**Comment by mganss** [comment]
Both implemented in v1.2.71. Open msg is Windows only for now. Also you can now open the script file using the context menu like you would a subpatch.
