### ISSUE TITLE
Raspberry Pi, armv7l-32

### ISSUE THREAD

**Issue by woollybird** [mganss/pdjs#3]
Hi Mganss,

Thanks for this external, this is a great tool ! I have tested it on Mac and Linux computers with Pd-vanilla and Purr-data : it works like a charm.

However, I have an issue on my Raspberry Pi (Rpi-4-4Gb). I run Pd on the Blokas [Patchbox OS](https://blokas.io/patchbox-os) based on the official Raspberry Pi OS and when I'm trying to use the pdjs external, I get this Pd error message :

``` Pd
/home/patch/Documents/Pd/externals/pdjs/js.pd_linux: wrong ELF class: ELFCLASS64
 js 
... couldn't create
```

Pure-data seems to use the *.pd_linux library that I supposed is the amd32-64 one. So I tried to only keep the *.l_arm64 lib in te pdjs directory but this time, Pd  simply did not recognize the lib and I had this single issue :

``` Pd
 js 
... couldn't create
```
I tried to rename the js.l_arm64 lib file in js.pd_linux, but same result :

``` Pd
/home/patch/Documents/Pd/externals/pdjs/js.pd_linux: wrong ELF class: ELFCLASS64
 js 
... couldn't create
```

I guess I get this error message because the external library was compiled for arm64 and not arm32 (armv7l specifically in this case). However, it's specified here that the library should be available for Linux-arm64-32. Is this a label error or should it work fine ? If not, could you please explain how to compile the library for arm32 architectures like armv6, armv7 for example ?

It could be very useful to run this lib on Raspberry's Pd.
Thanks a lot for your work again 👍 

M

**Comment by mganss** [comment]
pdjs is currently only available for arm64 (aka aarch64), not arm32 (aka armhf).

> However, it's specified here that the library should be available for Linux-arm64-32. Is this a label error or should it work fine ?

The "-32" at the end refers to the width of the floating point numbers PD uses, i.e. in this case floats (not doubles). This is still the standard in PD land.

I'll try and add a build for arm32 soon.

**Comment by woollybird** [comment]
Thanks a lot for your interesting answer ! I didn't know about this semantic for the differents architectures.
Let me know how the build process is doing,
Best.

**Comment by mganss** [comment]
v1.2.74 is now available for arm-linux  on deken. Tested on Raspberry Pi 3B. On deken, the architecture is called `Linux-armv8-32` but it runs fine on the Raspberry Pi 3B with Raspbian where the output of `uname -m` is `armv7l`.

On the Pi the default platform is shown as `Linux-armv6-32` in the deken UI which means you'll have to either uncheck "Hide foreign architectures?" or select "User-defined platform" and enter `Linux-armv8-32`.
