### ISSUE TITLE
Using async functions in pdjs

### ISSUE THREAD

**Issue by Garrettlynch** [mganss/pdjs#5]
I'm attempting to create a script that does json parsing with pdjs - many of the other Puredata libraries that do this seem to have issues or not be available for certain platforms so javascript/pdjs seems like a good solution.  Below is what I have so far - works just fine in a browser with the post(0 and outlet() swapped out for console.log(). In Puredata it does not work. The await seems to be ignored and the script continues to execute to the end resulting in empty output. According to to the Google's V8 JavaScript engine documentation async functions should work well so is there an issue with this that is specific to pdjs?

```
// Number of inlets and outlets for the Puredata object
inlets = 1;
outlets = 1;

// To test
//const json = JSON.parse('{"name":"John", "age":30, "city":"New York"}');
const json = {};

async function getjson(url)
{
    //another json to test
    //url = 'https://jsonware.com/json/abfe005c41c8214e22e487b8d6eff417.json';
    
	post("request made");

	// Wait on the fetching of the JSON
	const response = await (await fetch(url));

	if (!response.ok)
	{
   		//console.warn("request failed: ", response.status);
   		post("request failed");
   		return;
	}

	if (response.ok)
	{
   		post("request success");
   	}
   	
	const json = await response.json();
        await outlet(0, json.url);

    // Return the JSON object
    return;
}



function load()
{
	// Retrieve the passed url
	let url = arguments[0];

	// Define result variable
	let result;

	// if an argument was passed
	if (url)
	{
		// Call the getjson async function to retrieve the json
		let g = getjson(url);
	}
	else
	{
		// Send 'error' out the outlet
		result = "error";
		outlet(0, result)
	}

	// to test via the pd window
	//post(result);
}
```

**Comment by mganss** [comment]
There is no async support in pdjs. I'm not even sure how async functions could work within PD's execution model. It would probably require processing asynchronous functions on a separate thread.

**Comment by Garrettlynch** [comment]
Thanks for confirming what I suspected.
