### ISSUE TITLE
Text editor not opening on Windows (compiled on MSYS platform)

### ISSUE THREAD

**Issue by pd-l2ork** [mganss/pdjs#6]
Hi,

I am wondering if you may be aware of any issues with right-click->open option on Windows? For some reason, the text editor never opens on Windows when using this option. Thanks.

**Comment by mganss** [comment]
The file needs to exist already, i.e. you need to create the js object and include the file name, e.g. `js xyz.js` where xyz.js is an existing file.

**Comment by pd-l2ork** [comment]
Thank you for your reply. I just realized that Windows OS has to have a default app set for .js files. Once that is done, everything works as advertised. Otherwise, nothing happens when the open command is issued to the ja object. I added this important bit in the js help file that is now included with the pd-l2ork release. (Pd-L2Ork is a monolithic release that comes prepackaged with pdjs).

**Comment by mganss** [comment]
@pd-l2ork Thanks for maintaining Pd-L2Ork ❤️
